### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by TeaqariaWTF** [liemoe/moeGramX#1]
Hi ,

I just discovered the app. The best telegram fork I've ever used.

I have a few features I want, I hope it's possible.

skip to the next channel.Many telegram alternative apps also have this feature, I hope moegramx will also be available.
There is a vibration feature when jumping to the next channel, this feature should be able to be turned off and on. Vibration should be added.

blocking sponsored ads
![Screenshot_20230729-005942_moeGramX](https://github.com/liemoe/moeGramX/assets/90970076/cdcc14f7-b742-4377-9a59-44f874d3fa27)

copy feature. Some groups and channels do not allow copying. There must be a way to turn this off.
I hope the copy feature will be added to all channels and groups

**Comment by jplie** [comment]
Hey, jump to the next feature is originally exist in telegram but not supported in tgx and I can't implement it . Copying in the non-copy channels is also cannot be implemented now as it violates Telegram Terms of Use and client may be banned for this but I don't deny that it may exist as a feature in a fork or a FOSS version of client
